---

- pacman: name=squid,polkit state=installed
  sudo: yes
  notify: restart squid

- name: configure squid
  sudo: yes
  template:
    src: squid.conf
    dest: '{{ squid_conf }}'
  notify: restart squid
